/**
 * CLASSNAME_UTILITIES
 *
 * Purpose: Merges conditional Tailwind class names without conflicting utility declarations.
 * Connections: Shared UI primitives such as components generated by shadcn/ui.
 * Risk: Low because the helper performs presentation-only string composition.
 */
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
